name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Use this template to report bugs, errors, or unexpected behavior.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: What went wrong?
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Run command '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened instead?

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe the actual behavior

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Relevant environment details (OS, Python version, package versions, etc.)
      placeholder: |
        - OS: [e.g., Ubuntu 22.04]
        - Python version: [e.g., 3.11.5]
        - Package versions: [e.g., torch==2.1.0]
      value: |
        - OS:
        - Python version:
        - Package versions:

  - type: textarea
    id: error-logs
    attributes:
      label: Error Logs
      description: If applicable, add error logs or stack traces.
      placeholder: Paste error logs here
      render: shell

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (screenshots, related issues, potential fixes).
      placeholder: Any additional information that might be helpful
